laravel/app/Http/routes.php
// Route::get('/page/category/{id}/{page?}',array('as' => 'home.category', 'uses' => 'HomeController@category'));


Route::get('/media/korlantas={id}/{idchild?}',array('as' => 'home.portfolio', 'uses' => 'HomeController@portfolio'));
Route::get('/media/type={id}/{idchild?}',array('as' => 'home.type', 'uses' => 'HomeController@portfolioType'));
Route::get('/page/rss/{id}/{page?}',array('as' => 'home.rss', 'uses' => 'HomeController@rss'));
Route::post('/cari',array('as' => 'home.search', 'uses' => 'HomeController@search'));
// Route::post('/search',array('as' => 'home.search', 'uses' => 'HomeController@search'));
// Route::post('/comment', array('as' => 'home.comment', 'uses' => 'HomeController@comment'));
// Route::get('/ongkir', array('as' => 'home.ongkir', 'uses' => 'HomeController@getOngkir'));
// Route::post('/ongkir', array('as' => 'home.ongkir.store', 'uses' => 'HomeController@postOngkir'));
//Route::get('/member/{kode}', array('as' => 'home.member', 'uses' => 'HomeController@getMember'));
// Route::get('/tracking', array('as' => 'home.tracking', 'uses' => 'HomeController@getFack'));
// Route::post('/tracking', array('as' => 'home.tracking.store', 'uses' => 'HomeController@postCinta'));
// Route::get('/ongkir-international', array('as' => 'home.ongkirint', 'uses' => 'HomeController@getOngkirInt'));
// Route::post('/ongkir-international', array('as' => 'home.ongkirint.store', 'uses' => 'HomeController@postOngkirInt'));
// Route::get('/custom', 'HomeController@maudy');


//Route::get('protected', ['middleware' => ['auth', 'admin'], function() 
Route::group(['middleware' => ['auth', 'admin']], function()
{

	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'vrs-admin.admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'vrs-admin.admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'vrs-admin.post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'vrs-admin.post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'vrs-admin.post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'vrs-admin.product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'vrs-admin.product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'vrs-admin.event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'vrs-admin.event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');

	Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
	Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
	Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
	Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'vrs-admin.testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'vrs-admin.testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'vrs-admin.category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'vrs-admin.category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'vrs-admin.product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'vrs-admin.product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'vrs-admin.achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'vrs-admin.achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'vrs-admin.tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'vrs-admin.media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'vrs-admin.slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'vrs-admin.cctv.delete','uses' => 'CCTVController@destroy'));

	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'vrs-admin.file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'vrs-admin.file.delete','uses' => 'FileController@destroy'));
	Route::get('vrs-admin/file/featured/{id}', array('as' => 'vrs-admin.file.featured','uses' => 'FileController@featured'));
	Route::resource('vrs-admin/file', 'FileController');

	Route::get('vrs-admin/video/getMedia/{name}','VideoController@getMedia');
	Route::get('vrs-admin/video/{video}/delete',array('as'=> 'vrs-admin.video.delete','uses' => 'VideoController@destroy'));
	Route::get('vrs-admin/video/featured/{id}', array('as' => 'vrs-admin.video.featured','uses' => 'VideoController@featured'));
	Route::resource('vrs-admin/video', 'VideoController');

	Route::resource('vrs-admin/theme', 'ThemeController');
	Route::get('vrs-admin/club/{club}/delete',array('as'=> 'vrs-admin.club.delete','uses' => 'ClubController@destroy'));
	Route::resource('vrs-admin/club', 'ClubController');

	Route::get('vrs-admin/portfolio/enabled/{id}/{menu}',array('as'=> 'vrs-admin.portfolio.enabled','uses' => 'PortfolioController@enabled'));
	Route::get('vrs-admin/portfolio/featured/{id}', array('as' => 'vrs-admin.portfolio.featured','uses' => 'PortfolioController@featured'));
	Route::get('vrs-admin/portfolio/{menu}/delete',array('as'=> 'vrs-admin.portfolio.delete','uses' => 'PortfolioController@destroy'));


	Route::get('vrs-admin/detailportfolio/{menu}/delete',array('as'=> 'vrs-admin.detailportfolio.delete','uses' => 'DetailPortfolioController@destroy'));
	Route::resource('vrs-admin/detailportfolio', 'DetailPortfolioController');

	Route::get('vrs-admin/portfolio/getAllData',array('as' => 'vrs-admin.portfolio.api.getall','uses' => 'PortfolioController@getAllData'));
	Route::resource('vrs-admin/portfolio', 'PortfolioController');

	Route::get('vrs-admin/menu/{menu}/delete',array('as'=> 'vrs-admin.menu.delete','uses' => 'MenuController@destroy'));
	Route::resource('vrs-admin/menu', 'MenuController');
	Route::get('vrs-admin/menu/detail/{menu}/delete',array('as'=> 'vrs-admin.menu.detail.delete','uses' => 'MenuDetailController@destroy'));
	Route::get('vrs-admin/menu/detail/getjson',array('as'=> 'vrs-admin.menu.detail.getjson','uses' => 'MenuDetailController@getjson'));
	Route::resource('vrs-admin/menu/detail', 'MenuDetailController');

	Route::resource('vrs-admin/ujian', 'UjianController');
	Route::get('vrs-admin/ujian/{ujian}/delete',array('as'=> 'vrs-admin.ujian.delete','uses' => 'UjianController@destroy'));

	Route::resource('vrs-admin/soal', 'SoalController');
	Route::get('vrs-admin/soal/{soal}/delete',array('as'=> 'vrs-admin.soal.delete','uses' => 'SoalController@destroy'));

	Route::post('vrs-admin/general/upload',array('as' => 'vrs-admin.general.upload', 'uses' => 'GeneralController@upload'));
	Route::resource('vrs-admin/general', 'GeneralController');

	Route::get('vrs-admin/contact/enabled/{id}',array('as' => 'vrs-admin.contact.enabled', 'uses' => 'ContactController@enabled'));
	Route::get('vrs-admin/contact/{contact}/delete',array('as'=> 'vrs-admin.contact.delete','uses' => 'ContactController@destroy'));
	Route::resource('vrs-admin/contact', 'ContactController');

	Route::any('/imglist', ['as'=>'imglist', 'uses'=>'FileBrowserController@imageList']);
	//Image upload

	Route::any('/upload', [ 'uses' =>'FileBrowserController@index']);

	Route::get('vrs-admin/rss/getAllAjax',array('as' => 'vrs-admin.rss.api.getall','uses' => 'RssController@getAllAjax'));

laravel/app/Http/Controllers/GeraiController.php
<?php namespace App\Http\Controllers;
/*
lapantiga.com | Web & Mobile App Developer. Jl. Gubeng Kertajaya 9C no.27 A Surabaya - Indonesia, +62.856.3437.495 
*/

use App\Http\Controllers\Controller;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Requests\GeraiRequest;
use Session;
use App\gerai;
use App\geraiDetail;
use App\Media;
use App\Gender;
use App\City;

use DateTime;
use DB;

class GeraiController extends BasicController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$data['content'] = DB::table('ms_gerai')->orderBy('id', 'desc')->get();
		return view('page.gerai.index')->with('data',$data);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(GeraiRequest $request)
	{
		DB::table('ms_gerai')->insert([
				'title' => $request->title,
				'description' => $request->description,
				'address' => $request->address,
				'created_at' => new DateTime(),
				'updated_at' => new DateTime()
			]);
		Session::flash('success','Registrasi berhasil');
		return redirect('vrs-admin/gerai');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['content'] = DB::table('ms_gerai')->where('id', $id)->first();
		if (empty($data['content']))
			redirect('vrs-admin/gerai');
		return view('page.gerai.edit',compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(GeraiRequest $request, $id)
	{
		DB::table("ms_gerai")->where('id', $id)->update([
				'title' => $request->title,
				'description' => $request->description,
				'address' => $request->address,
				'updated_at' => new DateTime()
			]);
		Session::flash('success','Data berhasil diupdate');
		return redirect('vrs-admin/gerai');
		// $this->edit($id);
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		DB::table('ms_gerai')->where('id', $id)->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.gerai.index');
	}

	public function featured($id)
	{
		$data = gerai::find($id);
		if(empty($data))
		{
			return;
		}
		if($data->active == '1')
		{
			$data->active = '0';
		}else{
			$data->active = '1';
		}
		$data->save();
		return;
	}

	function getCoordinatesFromMitra($address, $city)
	{
		$coord = $this->getCoordinates($address);
		if($coord == 'null')
		{
			$coord = $this->getCoordinates($address.", ".$city);
			if($coord == 'null')
			{
				$coord = $this->getCoordinates($city);
				if($coord == 'null')
					$coord = 'null';
			}
		}
		//echo $coord."<br>";
		return $coord;
	}

	function getCoordinates($address) 
	{ 
		$key1 = "AIzaSyDenG9f8NSuPaEkFoxpMpHZrs3DyMHsBSk";
		$key2 = "AIzaSyAbcKfXVS-7CROSC5Jafzv5yjEzbqtuIno";
		$key3 = "AIzaSyDcvXhVNEmgLApyxwQl5QXWKTZj-uQveOg";
		$key = $key1;
		//echo $address."<br>";
		$address = str_replace(" ", "+", $address); // replace all the white space with "+" sign to match with google search pattern		 
		$url = "https://maps.google.com/maps/api/geocode/json?key=$key&sensor=false&address=$address";		 
		//echo $url."<br>";
		//$response = file_get_contents($url);		 
		$response = "";
		$json = json_decode($response,TRUE); //generate array object from the response from the web	
		//echo $response."<br>";
		if(count ($json['results'])	> 0)
			return ($json['results'][0]['geometry']['location']['lat'].",".$json['results'][0]['geometry']['location']['lng']);	 		
		return 'null';
	}

	function updateAllCoordMitra()
	{
		$allgerai = gerai::where('ms_privilige_id', '2')->get();
		foreach ($allgerai as $row) 
		{
			if($row->detail->latitude == "" || $row->detail->longitude == "" || $row->detail->latitude == "0" || $row->detail->longitude == "0")
			{
				$tmpCoord = "0,0";
				$tmpCoord = $this->getCoordinatesFromMitra($row->detail->address, $row->detail->city->name);
				if($tmpCoord == 'null')
				{
					$tmpCoord = $this->getCoordinates($row->detail->address.", ".$row->detail->city->name);
					if($tmpCoord == 'null')
					{
						$tmpCoord = $this->getCoordinates($row->detail->city->name);
						if($tmpCoord == 'null')
							$tmpCoord = "0,0";
					}
				}
	    		//echo $tmpCoord."<br>";
	    		$tmpCoord = explode(',', $tmpCoord);
	    		$latitude = $tmpCoord[0];
	    		$longitude = $tmpCoord[1];

				$row->detail->update(array(
					'latitude' => $latitude,
					'longitude' => $longitude
					));
	    		$row->detail->save();
	    		// echo $row->detail->latitude.",";
	    		// echo $row->detail->longitude."<br>";
			}
		}
	}

	function fillCustom()
	{
		$allgerai = gerai::where('ms_privilige_id', '2')->get();
		foreach ($allgerai as $row) 
		{
			if($row->detail->custom == "")
			{
				$row->detail->update(array(
					'custom' => $row->detail->panggilan
					));
	    		$row->detail->save();
			}
		}
	}

}

laravel/resources/views/page/gerai/create.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						TAMBAH MITRA BARU
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::open(array('url' => 'vrs-admin/gerai','method' => 'gerai')) !!}
					<div class="col-md-9">
              			@include('page.partials.notification')
						@include('page.errors.list')
	                  	<?php
		                    $arrGender = array();
		                    $arrCity = array();
		                    foreach($data['gender'] as $row)
		                    {
		                      $arrGender[$row->id] = $row->name;
		                    }
		                    foreach($data['city'] as $row)
		                    {
		                      $arrCity[$row->id] = $row->name;
		                    }
	                  	?>
						@include('page.gerai.form-create',['submitText' => 'Tambahkan'])
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')

@endsection

@section('custom-head')

@stop
@section('custom-footer')
	@include('page.scripts.media')
	<script type="text/javascript">
					$(document).ready(function() {
						// var reference = (function tipeportfolio(){
						// 	var type = $('#type').val();
						// 	switch(type){
						// 		case '1':
						// 			$('#mediaformcontainer').show();
						// 		break;
						// 		case '2':
						// 			$('#mediaformcontainer').hide();
						// 		break;
						// 	}
						//     return tipeportfolio;
						// }());
						// $('#type').change(function(){
						// 	reference();
						// 	console.log("ganti");
						// });
					});
					</script>
	<script type="text/javascript" src="('plugins/jqueryValidation/jquery.validate.min.js') "></script>
	<script type="text/javascript" src="('plugins/tinymce/js/tinymce/tinymce.min.js') "></script>


@stop

laravel/resources/views/page/gerai/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						EDIT MITRA
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['GeraiController@update',$data['content']->id],'method' => 'PATCH')) !!}
					<div class="col-md-9">
              			@include('page.partials.notification')
						@include('page.errors.list')
	                  	
						@include('page.gerai.form-create',['submitText' => 'Perbarui'])
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.partials.media')
@endsection

@section('custom-head')

@stop
@section('custom-footer')

@stop

laravel/resources/views/page/gerai/form-create.blade.php
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('title','Nama Gerai : ') !!}
							{!! Form::text('title',null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('description','Deskripsi Gerai : ') !!}
							{!! Form::textarea('description',null, ['class' => 'form-control', 'rows' => 3]) !!}
						</div>
					</div>
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('address','Alamat Gerai : ') !!}
							{!! Form::textarea('address',null, ['class' => 'form-control', 'rows' => 3]) !!}
						</div>
					</div>
					<div class="form-group col-md-12">
						{!! Form::submit($submitText,['class' => 'btn btn-info']) !!}
					</div>

laravel/resources/views/page/gerai/form.blade.php
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('title','Nama Gerai : ') !!}
							{!! Form::text('title',null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('title','Nama Gerai : ') !!}
							{!! Form::textarea('title',null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group">
						<div class="form-group col-md-12">
							{!! Form::label('title','Nama Gerai : ') !!}
							{!! Form::textarea('title',null, ['class' => 'form-control']) !!}
						</div>
					</div>
					<div class="form-group col-md-12">
						{!! Form::submit($submitText,['class' => 'btn btn-info']) !!}
					</div>

laravel/resources/views/page/gerai/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Gerai SIM
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<div class="col-md-3">
						<div class="row">
						{!! Form::open(array('url' => 'vrs-admin/gerai','method' => 'gerai')) !!}
						<div class="col-md-12">
	              			@include('page.partials.notification')
							@include('page.errors.list')
							@include('page.gerai.form-create',['submitText' => 'Tambahkan'])
						</div>
						{!! Form::close() !!}
						</div>
					</div>
					<div class="col-md-9">
						<table class="table" id="dataTables">
							<thead>
								<tr>
									<th>&nbsp;</th>
									<th>Nama </th>
									<th>Deskripsi </th>
									<th>Alamat</th>
									<th>Peta</th>
								</tr>
							</thead>
							<tbody>
								<?php $i = 1; ?>
								@foreach($data['content'] as $row)
								<tr>
									<td>{{ $i++ }}</td>
									<td>
										{{ $row->title }}
										<div class="action-post-hover">
											<a href="{{route('vrs-admin.gerai.edit',[ $row->id ])}}">edit</a>
											<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('vrs-admin.gerai.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
										</div>
									</td>
									<td>{{ $row->description }}</td>
	                          		<td>{{ $row->address }}</td>
									<td></td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
	$('#dataTables').on('click', '.Switch', function()  {
		var id_post = $(this).data("id");
		setFeatured(id_post);
		$(this).toggleClass('On').toggleClass('Off');
	});
	function setFeatured(id)
	{
		var url = "{{ URL::to('vrs-admin/gerai/featured') }}/" + id +"";
		$.ajax(url)
		.done(function() {
			
		})
		.fail(function() {
			alert( "error" );
		});
	}
</script>
@stop