laravel/app/Http/routes.php
Route::get('/api/getvideo',array('as' => 'api.getvideo', 'uses' => 'MobileServiceController@getVideo'));
Route::get('/api/getphoto',array('as' => 'api.getphoto', 'uses' => 'MobileServiceController@getPhoto'));
Route::get('/api/getpdfuser',array('as' => 'api.getpdfuser', 'uses' => 'MobileServiceController@getPdfUser'));
Route::get('/api/getpdfumum',array('as' => 'api.getpdfumum', 'uses' => 'MobileServiceController@getPdfUmum'));
Route::get('/api/getpdfall',array('as' => 'api.getpdfall', 'uses' => 'MobileServiceController@getPdfAll'));
Route::get('/api/getevent',array('as' => 'api.getevent', 'uses' => 'MobileServiceController@getEvent'));
Route::get('/api/getmitra',array('as' => 'api.getmitra', 'uses' => 'MobileServiceController@getMitra'));
Route::get('/api/getmitraid/{id}',array('as' => 'api.getmitraid', 'uses' => 'MobileServiceController@getMitraId'));
//Route::get('/api/getmitracity/{id}',array('as' => 'api.getmitracity', 'uses' => 'MobileServiceController@getMitraCity'));
Route::get('/api/gettestimoni',array('as' => 'api.gettestimoni', 'uses' => 'MobileServiceController@getTestimoni'));
Route::get('/api/getarticles',array('as' => 'api.getarticles', 'uses' => 'MobileServiceController@getArticles'));
Route::get('/api/gettechnology',array('as' => 'api.gettechnolgoy', 'uses' => 'MobileServiceController@getTechnology'));
Route::post('/api/login',array('as' => 'api.login', 'uses' => 'MobileServiceController@login'));
Route::post('/api/register',array('as' => 'api.register', 'uses' => 'MobileServiceController@register'));
Route::post('/api/contactus',array('as' => 'api.contactus', 'uses' => 'MobileServiceController@contactUs'));
Route::post('/api/resetpass',array('as' => 'api.resetpass', 'uses' => 'MobileServiceController@resetPass'));
Route::get('/api/getcity',array('as' => 'api.getcity', 'uses' => 'MobileServiceController@getCity'));
Route::get('/api/getcity/{id}',array('as' => 'api.getcity', 'uses' => 'MobileServiceController@getMitraCity'));
Route::get('/api/getgender',array('as' => 'api.getgender', 'uses' => 'MobileServiceController@getGender'));
Route::get('/api/pushnot',array('as' => 'api.pushnot', 'uses' => 'MobileServiceController@pushNot'));
Route::get('/api/aboutus',array('as' => 'api.aboutUs', 'uses' => 'MobileServiceController@aboutUs'));
Route::get('/api/getleveluk',array('as' => 'api.getleveluk','uses'=> 'MobileServiceController@getLevelUk'));
Route::get('/api/gettestimonikesehatan',array('as' => 'api.gettestimonikesehatan', 'uses' => 'MobileServiceController@getTestimoniKesehatan'));
Route::get('/api/gettestimonibisnis',array('as' => 'api.gettestimonibisnis', 'uses' => 'MobileServiceController@getTestimoniBisnis'));
Route::get('/api/getcredit',array('as' => 'api.getcredit','uses'=> 'MobileServiceController@getCredit'));
Route::get('/api/getphotoalbum',array('as' => 'api.getphotoalbum','uses'=> 'MobileServiceController@getPhotoAlbum'));
Route::get('/api/getnotification',array('as' => 'api.getnotification','uses'=> 'MobileServiceController@getNotification'));
// Route::get('/page/portfolio/{id}/{idchild?}',array('as' => 'home.portfolio', 'uses' => 'HomeController@portfolio')); 
// Route::get('/page/post/{id}/{page?}',array('as' => 'home.post', 'uses' => 'HomeController@post'));
// Route::get('/page/category/{id}/{page?}',array('as' => 'home.category', 'uses' => 'HomeController@category'));


Route::get('/media/korlantas={id}/{idchild?}',array('as' => 'home.portfolio', 'uses' => 'HomeController@portfolio'));
Route::get('/media/type={id}/{idchild?}',array('as' => 'home.type', 'uses' => 'HomeController@portfolioType'));
Route::get('/page/rss/{id}/{page?}',array('as' => 'home.rss', 'uses' => 'HomeController@rss'));
Route::post('/cari',array('as' => 'home.search', 'uses' => 'HomeController@search'));
// Route::post('/search',array('as' => 'home.search', 'uses' => 'HomeController@search'));
// Route::post('/comment', array('as' => 'home.comment', 'uses' => 'HomeController@comment'));
// Route::get('/ongkir', array('as' => 'home.ongkir', 'uses' => 'HomeController@getOngkir'));
// Route::post('/ongkir', array('as' => 'home.ongkir.store', 'uses' => 'HomeController@postOngkir'));
//Route::get('/member/{kode}', array('as' => 'home.member', 'uses' => 'HomeController@getMember'));
// Route::get('/tracking', array('as' => 'home.tracking', 'uses' => 'HomeController@getFack'));
// Route::post('/tracking', array('as' => 'home.tracking.store', 'uses' => 'HomeController@postCinta'));
// Route::get('/ongkir-international', array('as' => 'home.ongkirint', 'uses' => 'HomeController@getOngkirInt'));
// Route::post('/ongkir-international', array('as' => 'home.ongkirint.store', 'uses' => 'HomeController@postOngkirInt'));
// Route::get('/custom', 'HomeController@maudy');


//Route::get('protected', ['middleware' => ['auth', 'admin'], function() 
Route::group(['middleware' => ['auth', 'admin']], function()
{

	Route::get('vrs-admin', 'AdminController@index');
	Route::get('vrs-admin/createnotification', 'AdminController@createNotification');
	Route::post('vrs-admin/password', array('as' => 'vrs-admin.admin.password', 'uses' => 'AdminController@Changepassword'));
	Route::get('vrs-admin/password', array('as' => 'vrs-admin.admin.password', 'uses' => 'AdminController@password'));

	Route::get('vrs-admin/post/getAllAjax',array('as' => 'vrs-admin.post.api.getall','uses' => 'PostController@getAllAjax'));
	Route::get('vrs-admin/post/{post}/delete',array('as'=> 'vrs-admin.post.delete','uses' => 'PostController@destroy'));
	Route::get('vrs-admin/post/featured/{id}', array('as' => 'vrs-admin.post.featured','uses' => 'PostController@featured'));
	Route::resource('vrs-admin/post', 'PostController');

	Route::resource('vrs-admin/aduan', 'AduanController');
	Route::get('vrs-admin/replyForm/{id}', ['as' => 'vrs-admin.aduan.replyForm', 'uses' => 'AduanController@replyForm']);
	Route::post('vrs-admin/reply/{id}', ['as' => 'vrs-admin.aduan.reply', 'uses' => 'AduanController@reply']);

	Route::get('vrs-admin/product/getAllAjax',array('as' => 'vrs-admin.product.api.getall','uses' => 'ProductController@getAllAjax'));
	Route::get('vrs-admin/product/{product}/delete',array('as'=> 'vrs-admin.product.delete','uses' => 'ProductController@destroy'));
	Route::resource('vrs-admin/product', 'ProductController');

	Route::get('vrs-admin/event/getAllAjax',array('as' => 'vrs-admin.event.api.getall','uses' => 'EventController@getAllAjax'));
	Route::get('vrs-admin/event/{event}/delete',array('as'=> 'vrs-admin.event.delete','uses' => 'EventController@destroy'));
	Route::resource('vrs-admin/event', 'EventController');

	Route::get('vrs-admin/gerai/getAllAjax',array('as' => 'vrs-admin.gerai.api.getall','uses' => 'GeraiController@getAllAjax'));
	Route::get('vrs-admin/gerai/{gerai}/delete',array('as'=> 'vrs-admin.gerai.delete','uses' => 'GeraiController@destroy'));
	Route::get('vrs-admin/gerai/featured/{id}', array('as' => 'vrs-admin.gerai.featured','uses' => 'GeraiController@featured'));
	Route::resource('vrs-admin/gerai', 'GeraiController');

	Route::get('vrs-admin/testi/getAllAjax',array('as' => 'vrs-admin.testi.api.getall','uses' => 'LeadersController@getAllAjax'));
	Route::get('vrs-admin/testi/{leader}/delete',array('as'=> 'vrs-admin.testi.delete','uses' => 'LeadersController@destroy'));
	Route::resource('vrs-admin/testi', 'LeadersController');

	Route::get('vrs-admin/category/storeAjax','CategoryController@storeAjax');
	Route::get('vrs-admin/category/{post}/delete',array('as'=> 'vrs-admin.category.delete','uses' => 'CategoryController@destroy'));
	Route::get('vrs-admin/category/getAllAjax',array('as' => 'vrs-admin.category.api.getall','uses' => 'CategoryController@getAllAjax'));
	Route::resource('vrs-admin/category', 'CategoryController');

	Route::get('vrs-admin/product-category/storeAjax','ProductCategoriesController@storeAjax');
	Route::get('vrs-admin/product-category/{product}/delete',array('as'=> 'vrs-admin.product-category.delete','uses' => 'ProductCategoriesController@destroy'));
	Route::get('vrs-admin/product-category/getAllAjax',array('as' => 'vrs-admin.product-category.api.getall','uses' => 'ProductCategoriesController@getAllAjax'));
	Route::resource('vrs-admin/product-category', 'ProductCategoriesController');

	Route::get('vrs-admin/achievement/storeAjax','AchievementController@storeAjax');
	Route::get('vrs-admin/achievement/{leader}/delete',array('as'=> 'vrs-admin.achievement.delete','uses' => 'AchievementController@destroy'));
	Route::get('vrs-admin/achievement/getAllAjax',array('as' => 'vrs-admin.achievement.api.getall','uses' => 'AchievementController@getAllAjax'));
	Route::resource('vrs-admin/achievement', 'AchievementController');

	Route::get('vrs-admin/tag/storeAjax','TagController@storeAjax');
	Route::get('vrs-admin/tag/{tag}/delete',array('as'=> 'vrs-admin.tag.delete','uses' => 'TagController@destroy'));
	Route::resource('vrs-admin/tag', 'TagController');

	Route::post('vrs-admin/media/storeAjax','MediaController@storeAjax');
	Route::get('vrs-admin/media/getAllData','MediaController@getAllData');
	Route::get('vrs-admin/media/getMedia/{name}','MediaController@getMedia');
	Route::get('vrs-admin/media/{media}/delete',array('as'=> 'vrs-admin.media.delete','uses' => 'MediaController@destroy'));
	
	Route::resource('vrs-admin/media', 'MediaController');
	Route::get('vrs-admin/slider/{slider}/delete',array('as'=> 'vrs-admin.slider.delete','uses' => 'SliderController@destroy'));
	Route::resource('vrs-admin/slider', 'SliderController');

	Route::resource('vrs-admin/cctv', 'CCTVController');
	Route::get('vrs-admin/cctv/{cctv}/delete',array('as'=> 'vrs-admin.cctv.delete','uses' => 'CCTVController@destroy'));

	Route::get('vrs-admin/file/getMedia/{name}','FileController@getMedia');
	//Route::post('vrs-admin/file/create',array('as'=> 'vrs-admin.file.create','uses' => 'FileController@create'));
	Route::get('vrs-admin/file/{file}/delete',array('as'=> 'vrs-admin.file.delete','uses' => 'FileController@destroy'));

laravel/app/Media.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Media extends Model {

	protected $table = 'ms_medias';
	protected $fillable = array('file','mime','caption','alternate_text','description','isumum');
	public $timestamps = true;

    public function post()
    {
        return $this->belongsToMany('App\Post','tr_media_posts','ms_media_id','ms_post_id');
    }
    public function portfolio()
    {
    	return $this->hasMany('App\Portfolio','ms_media_id','id');
    }
    public function logs()
    {
        return $this->morphMany('App\Log', 'logable');
    }
}

laravel/app/Http/Controllers/MediaController.php
<?php namespace App\Http\Controllers;
/*
lapantiga.com | Web & Mobile App Developer. Jl. Gubeng Kertajaya 9C no.27 A Surabaya - Indonesia, +62.856.3437.495 */

use App\Http\Controllers\BasicController;
use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Http\Requests\MediaRequest;
use App\Media;
use File;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Storage;
use Session;
use Image;
use Input;

class MediaController extends BasicController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	protected $path;
	function __construct() {
		$this->path = 'upload/media/';
	}
	public function index()
	{
		$data['content'] = Media::orderBy('created_at','desc')->get();
		return view('page.media.index',compact('data'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('page.media.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(MediaRequest $request)
	{
		$data = New Media;
		$fileName = '';
		if ($request->hasFile('file'))
		{
		    $file = $request->file('file');
			$extension = $file->getClientOriginalExtension();
			$fileName = 'img_'.date('Ymd_Hsi').'.'.$extension;
			$file->move($this->path,$fileName);
			$data->mime = $file->getClientMimeType();
			$img = Image::make($this->path.$fileName);
			$img->save($this->path.$fileName, 60);
		}
		
		$data->file = $fileName;
		$data->caption = $request->input('caption');
		$data->description = $request->input('description');
		$data->save();

		$log = array();
		$log['action'] = 'insert';
		$log['name'] = $fileName;
		$data->logs()->save($this->log($log));
		Session::flash('success','Data berhasil ditambahkan');
		return redirect()->route('vrs-admin.media.index');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$data['content']=Media::find($id);
		return view('page.media.edit',compact('data'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update(Request $request,$id)
	{
		$data = Media::find($id);
		$fileName = $data->file;

		if ($request->hasFile('file'))
		{
		    $file = $request->file('file');
			$extension = $file->getClientOriginalExtension();
			$fileName = 'img_'.date('Ymd_Hsi').'.'.$extension;

			$log = array();
			$log['action'] = 'update';
			$log['name'] = $data->file.' - '.$fileName;
			$data->logs()->save($this->log($log));


			$file->move($this->path,$fileName);
			$img = Image::make($this->path.$fileName);
			$img->save($this->path.$fileName, 60);
			if(File::exists('upload/media/'.$data->file))
			{
				File::delete('upload/media/'.$data->file);
			}

			$data->mime = $file->getClientMimeType();
		}else{
			$log = array();
			$log['action'] = 'update';
			$log['name'] = $data->caption;
			$data->logs()->save($this->log($log));
		}
		
		$data->file = $fileName;
		$data->caption = $request->input('caption');
		$data->description = $request->input('description');
		$data->save();

		

		return redirect()->route('vrs-admin.media.index');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$data = Media::find($id);
		\App\Post::where('ms_media_id',$id)->update(array('ms_media_id' => '0'));
		\App\DetailPortfolio::where('ms_media_id',$id)->delete();
		\App\Slider::where('ms_media_id',$id)->delete();
		$log = array();
		$log['action'] = 'delete';
		$log['name'] = $data->file;
		$data->logs()->save($this->log($log));
		$data->delete();
		Session::flash('success','Data berhasil dihapus');
		return redirect()->route('vrs-admin.media.index');
	}

	public function getAllData()
	{
		$offset = Input::get('offset');
		$data = null;
		if(empty($offset))
			$data = Media::orderBy('created_at','desc')->get()->take(12);
		else
			$data = Media::orderBy('created_at','desc')->skip($offset)->take(12)->get();
		return $data;
	}
	public function storeAjax(MediaRequest $request){
		$file = $request->file('file');
		$extension = $file->getClientOriginalExtension();
		$fileName = 'img_'.date('Ymd_Hsi').'.'.$extension;
		$file->move($this->path,$fileName);
		/*$img = Image::make($this->path.$fileName);
		$img->save($this->path.$fileName, 60);*/
		$data = new Media;
		$data->file = $fileName;
		$data->mime = $file->getClientMimeType();
		$data->save();
		$log = array();
		$log['action'] = 'insert';
		$log['name'] = $data->file;
		$data->logs()->save($this->log($log));

		return $data->file;
	}
	public function getMedia($fileName)
	{
		$data = Media::where('file',$fileName)->firstOrFail();
		$file = Storage::disk('local')->get($data->file);

		return (new Response($file,200))
			->header('Content-Type', $file->mime);
	}
}

laravel/resources/views/page/media/create.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Tambah Media
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::open(array('route' => 'vrs-admin.media.store', 'method' => 'post','files' => true)) !!}
					@include('page.errors.list')
					@include('page.media.form',['submitText' => 'Tambah'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

@section('custom-head')

@stop
@section('custom-footer')
<script src="{{ asset('plugins/bootstrapFileStyle/bootstrap-filestyle.min.js') }}"></script>
<script type="text/javascript">
	$('input[type=file]').filestyle();
</script>
@stop

laravel/resources/views/page/media/edit.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						Edit Media
					</h3>                                    
				</div>
				<div class="box-body">
					{!! Form::model($data['content'],array('action' => ['MediaController@update',$data['content']->id],'method' => 'PATCH','files' => true)) !!}
					@include('page.media.form',['submitText' => 'Perbarui'])
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
@endsection

@section('custom-head')

@stop
@section('custom-footer')
<script src="{{ asset('plugins/bootstrapFileStyle/bootstrap-filestyle.min.js') }}"></script>
<script type="text/javascript">
	$('input[type=file]').filestyle({buttonText : " Change Image" });
</script>
@stop

laravel/resources/views/page/media/form.blade.php
		<div class="form-group">
			{!! Form::label('file','File : ') !!}
			<div class="col-md-12" id="featuredImage">
			@if(isset($data['content']->file))
				<img src="{{asset('upload/media/'.$data['content']->file)}}" class="col-md-5 img-thumbnail">
			@endif
			</div>
			{!! Form::file('file', ['class' => 'form-control']) !!}
			
		</div>
		<div class="form-group">
			{!! Form::label('caption','Caption : ') !!}
			{!! Form::text('caption',null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('alternate_text','Alternate Text : ') !!}
			{!! Form::text('alternate_text',null, ['class' => 'form-control']) !!}
		</div>
		<div class="form-group">
			{!! Form::label('description','Deskripsi : ') !!}
			{!! Form::textarea('description',null, ['class' => 'form-control','id' => 'textEditor']) !!}
		</div>
		<div class="form-group">
			{!! Form::submit($submitText,['class' => 'btn btn-info']) !!}
		</div>

laravel/resources/views/page/media/index.blade.php
@extends('app')

@section('content')
<section class="content-header">
	<h1>
		Dashboard
		<small>Control panel</small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Dashboard</li>
	</ol>
</section>

<!-- Main content -->
<section class="content">

	<div class="row">
		<div class="col-xs-12">
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">
						MEDIA
						<a href="{{route('vrs-admin.media.create')}}" class="btn btn-default btn-add-new">Tambah Baru</a>
					</h3>                                    
				</div>
				<div class="box-body table-responsive">
					@include('page.partials.notification')
					<table class="table" id="dataTables">
						<thead>
							<tr>
								<th class="col-md-1">&nbsp;</th>
								<th class="col-md-9">File</th>
								<th class="col-md-2">Tanggal</th>
							</tr>
						</thead>
						<tbody>
							@foreach($data['content'] as $row)
							<tr>
								<td>&nbsp;</td>
								<td>
									<img src="{{ asset('upload/media/'.$row->file) }}" class="col-md-2" alt="{{$row->alt_text}}">

									{{ $row->caption }}
									<div class="action-post-hover">
										<a href="{{route('vrs-admin.media.edit',[ $row->id ])}}">edit</a>
										<a href="javascript:void(0);" onclick="deleteModal(this)" data-href="{!! route('vrs-admin.media.delete',[ $row->id ]) !!}" style="color:red;">trash</a>
									</div>
								</td>
								<td>{{ date('d-M-Y' ,strtotime($row->created_at)) }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</section>
@include('page.scripts.delete-modal')
@endsection

@section('custom-head')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/datatables/media/css/jquery.dataTables.css') }}">
@stop
@section('custom-footer')
<script type="text/javascript" src="{{ asset('plugins/datatables/media/js/jquery.dataTables.js') }}"></script>
<script type="text/javascript">
	$('#dataTables').DataTable();
	
</script>
@stop